# key mapping
## set prefix key
unbind-key C-b
set-option -g prefix C-t
## set key mode in copy mode
set-window-option -g mode-keys vi
## controll window (enable to controll with binding Ctrl-key)

## pane settings
bind ^ split-window -h
bind - split-window -v

# cursor settings
# set -g cursor-style bar

# color settings
## status line
set-option -g status-fg color15
set-option -g status-bg colour57
## pane border
set-option -g pane-border-style "fg=default"
set-option -g pane-active-border-style "bg=default"
set-option -ag pane-active-border-style "fg=default"

# select pane 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# copy mode settings
setw -g mode-keys vi
bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key p run "pbcopy | tmux load-buffer - ; tmux paste-buffer"

set -g mouse on 

# override setting
# source-file $HOME/.tmux.conf.local
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'violet'

run-shell '~/.tmux/plugins/tmux-power/tmux-power.tmux'

set -g window-style 'fg=default,bg=default'
set -g window-active-style 'fg=default,bg=default'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
