name: CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.nix"
      - "flake.lock"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nixos:
    name: Build NixOS (manix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Check flake evaluates
        run: nix flake check . --no-build
      - name: Build NixOS system closure
        run: make nix/check/manix

  # darwin:
  #   name: Build nix-darwin (MAOZBook)
  #   runs-on: macos-14
  #   steps:
  #     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
  #     - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
  #     - uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
  #     - name: Check flake evaluates
  #       run: nix flake check . --no-build
  #     - name: Build darwin system closure
  #       run: make nix/check/mac
